'''
Functions:
1.
a. Go to ex2_str exercise 1 (related to ex1_print_and_var exercise 2) 
and encapsulate the code in a function called “say_my_name()” which has no input 
and no output, but should print your name in a cool format.
Call the function and verify that it works.

b. Do a minimal effort documentation of the function
autogenerated by your editor, or formatted as we
showed in class.
'''

def say_my_name():
    my_name = r"""
          ___           ___           ___           ___           ___           ___     
         /\  \         /\  \         /\__\         /\  \         /\__\         /\  \    
        /::\  \       /::\  \       /::|  |        \:\  \       /:/  /        /::\  \   
       /:/\:\  \     /:/\:\  \     /:|:|  |         \:\  \     /:/  /        /:/\ \  \  
      /::\~\:\  \   /:/  \:\  \   /:/|:|  |__       /::\  \   /:/  /  ___   _\:\~\ \  \ 
     /:/\:\ \:\__\ /:/__/ \:\__\ /:/ |:| /\__\     /:/\:\__\ /:/__/  /\__\ /\ \:\ \ \__\
     \/__\:\/:/  / \:\  \ /:/  / \/__|:|/:/  /    /:/  \/__/ \:\  \ /:/  / \:\ \:\ \/__/
          \::/  /   \:\  /:/  /      |:/:/  /    /:/  /       \:\  /:/  /   \:\ \:\__\  
           \/__/     \:\/:/  /       |::/  /     \/__/         \:\/:/  /     \:\/:/  /  
                      \::/  /        /:/  /                     \::/  /       \::/  /   
                       \/__/         \/__/                       \/__/         \/__/    
                       
"""
print(my_name)